# version: "3.9" --> obsolete

services:
  # Η κύρια εφαρμογή (App)
  web:
    build: .  # Χρησιμοποιεί το Dockerfile του root
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: always

  # Το νέο service για το Questionnaire
  questionnaire:
    build:
      context: ./questionnaire  # Χρησιμοποιεί το φάκελο questionnaire
      dockerfile: Dockerfile    # Χρησιμοποιεί το Dockerfile μέσα στο questionnaire
    command: python manage.py runserver 0.0.0.0:8001 # Τρέχει σε άλλη πόρτα
    volumes:
      - ./questionnaire:/app
    ports:
      - "8001:8001" # Πρόσβαση από το localhost:8001
    env_file:
      - .env  # Χρησιμοποιούν τα ίδια διαπιστευτήρια βάσης
    depends_on:
      - db
    restart: always

  # Η κοινή βάση δεδομένων
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-energyguard}
      POSTGRES_USER: ${POSTGRES_USER:-energyguard_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testdatabase}
    restart: always

volumes:
  postgres_data:
  static_volume:
